#!/bin/bash
#
# Copyright © 2020 Filip Paskali
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

case $(cat /sys/bus/pci/devices/0000:00:01.0/power/runtime_status) in
    active)
      echo "$LABEL " 
      echo ""
      # echo "#77BA00"
      ;;
    suspended)
      echo "$LABEL "
      echo ""
      echo "#6E6E6E"
      ;;
esac

